### ISSUE TITLE
Builds fail on Ubuntu 20.04

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#348]
This test fails on a native Ubuntu 20.04 GHA runner:

```
//cas/worker:running_actions_manager_test    
```

The cargo build fails as well, leading me to believe that the two are related:

```
error[E0463]: can't find crate for `tokio_macros`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/lib.rs:647:13
    |
647 |     pub use tokio_macros::select_priv_declare_output_enum;
    |             ^^^^^^^^^^^^ can't find crate

   Compiling futures-util v0.3.29
error[E0463]: can't find crate for `tokio_macros`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/lib.rs:653:13
    |
653 |     pub use tokio_macros::select_priv_clean_pattern;
    |             ^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `tokio_macros`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/lib.rs:660:17
    |
660 |         pub use tokio_macros::main;
    |                 ^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `tokio_macros`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.33.0/src/lib.rs:665:17
    |
665 |         pub use tokio_macros::test;
    |                 ^^^^^^^^^^^^ can't find crate

   Compiling futures-macro v0.3.28
   Compiling futures-io v0.3.28
error[E0463]: can't find crate for `futures_macro`
 --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/stream_select_mod.rs:6:9
  |
6 | pub use futures_macro::stream_select_internal;
  |         ^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `futures_macro`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/join_mod.rs:84:9
   |
84 | pub use futures_macro::join_internal;
   |         ^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `futures_macro`
  --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/join_mod.rs:88:9
   |
88 | pub use futures_macro::try_join_internal;
   |         ^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `futures_macro`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/select_mod.rs:309:9
    |
309 | pub use futures_macro::select_internal;
    |         ^^^^^^^^^^^^^ can't find crate

error[E0463]: can't find crate for `futures_macro`
   --> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/async_await/select_mod.rs:313:9
    |
313 | pub use futures_macro::select_biased_internal;
    |         ^^^^^^^^^^^^^ can't find crate
```

**Comment by aaronmondal** [comment]
Builds on Ubuntu 20.04 are no longer supported. Please use `nix build` or the published containers on legacy systems.
